### ISSUE TITLE
Broken in node 0.5.9+

### ISSUE THREAD

**Issue by nomiddlename** [felixge/node-require-like#1]
Require.paths has been removed, and now throws an exception. Here's an example stacktrace from my test suite, which uses sandboxed-module.

module.js:376

```
throw new Error('require.paths is removed. Use ' +
      ^
```

Error: require.paths is removed. Use node_modules folders, or the NODE_PATH environment variable instead.
    at Function.<anonymous> (module.js:376:11)
    at requireLike (/Users/garethjones/log4js-node/node_modules/sandboxed-module/node_modules/require-like/lib/require-like.js:26:30)
    at SandboxedModule._resolveFilename (/Users/garethjones/log4js-node/node_modules/sandboxed-module/lib/sandboxed_module.js:68:19)
    at SandboxedModule._init (/Users/garethjones/log4js-node/node_modules/sandboxed-module/lib/sandboxed_module.js:48:8)
    at Function.load (/Users/garethjones/log4js-node/node_modules/sandboxed-module/lib/sandboxed_module.js:25:19)
    at Function.require (/Users/garethjones/log4js-node/node_modules/sandboxed-module/lib/sandboxed_module.js:32:15)
    at Object.<anonymous> (/Users/garethjones/log4js-node/test/fileAppender.js:154:44)
    at run (/Users/garethjones/log4js-node/node_modules/vows/lib/vows/suite.js:128:31)
    at EventEmitter.<anonymous> (/Users/garethjones/log4js-node/node_modules/vows/lib/vows/suite.js:201:40)
    at EventEmitter.emit (events.js:88:20)

**Comment by felixge** [comment]
Thanks for reporting this, but I don't support unstable node versions, so I won't get around to fixing this until 0.6 is released.

That being said, I would accept a pull request which fixes this for 0.6 and works in 0.4.

**Comment by felixge** [comment]
Fixed by merging #2. Thanks
