### ISSUE TITLE
Requiring relative paths not working?

### ISSUE THREAD

**Issue by broofa** [felixge/node-require-like#7]
I'd like to load modules relative to the `path` I passed to `requireLike`, but it doesn't seem to be working.   I feel like I'm missing something obvious... :-/

----
```
kieffer@MacBook-Pro-3$ pwd
/Users/kieffer/repos/node-require-like

kieffer@MacBook-Pro-3$ mkdir /tmp/foo

kieffer@MacBook-Pro-3$ touch /tmp/foo/bar.js

kieffer@MacBook-Pro-3$ node
> requireLike = require('.')
[Function: requireLike]
> myRequire = requireLike('/tmp/foo')
{ [Function: requireLike]
  resolve: [Function],
  paths: undefined,
  main: undefined,
  extensions: { '.js': [Function], '.json': [Function], '.node': [Function] },
  cache:
   { '/Users/kieffer/repos/node-require-like/lib/require-like.js':
      Module {
        id: '/Users/kieffer/repos/node-require-like/lib/require-like.js',
        exports: [Function: requireLike],
        parent: [Object],
        filename: '/Users/kieffer/repos/node-require-like/lib/require-like.js',
        loaded: true,
        children: [],
        paths: [Object] } } }
> myRequire('./bar')
Error: Cannot find module './bar'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at requireLike (/Users/kieffer/repos/node-require-like/lib/require-like.js:15:26)
    at repl:1:1
    at ContextifyScript.Script.runInThisContext (vm.js:23:33)
    at REPLServer.defaultEval (repl.js:339:29)
    at bound (domain.js:280:14)
    at REPLServer.runBound [as eval] (domain.js:293:12)
    at REPLServer.onLine (repl.js:536:10)
    at emitOne (events.js:101:20)
>
```

**Comment by broofa** [comment]
Ah, figured it out.  I need to be passing a path to an actual module file, not a module directory.

For anyone who's stumbles across this, you can set NODE_DEBUG=module to see node's module resolution debug output.  And doing `requireLike('/tmp/foo/index.js')` fixed the issue, above.
